apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload-type
                operator: In
                values:
                - backend
      containers:
      - name: backend
        image: 869935091451.dkr.ecr.ap-northeast-2.amazonaws.com/backend:241204-1
        ports:
        - containerPort: 8080              
        env:
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        volumeMounts:
        - name: mongo-certs
          mountPath: "/etc/ssl/certs"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: mongo-certs
        secret:
          secretName: mongodb-secret