apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYjovL2FkbWluMToxMTExMTExMUBkb2NkYi10ZXN0LmNsdXN0ZXItY3YwNmNjMHdtMWE4LmFwLW5vcnRoZWFzdC0yLmRvY2RiLmFtYXpvbmF3cy5jb206MjcwMTcvZG9jZGItdGVzdD9yZXBsaWNhU2V0PXJzMCZyZWFkUHJlZmVyZW5jZT1zZWNvbmRhcnlQcmVmZXJyZWQmcmV0cnlXcml0ZXM9ZmFsc2U=